remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: true
  24 hours: false

positions:
  - Software engineer
  - Internship

locations:
  - United States
  - Los Angeles

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'